version: '3.8'

services:
  pixel-play:
    container_name: pixel-play
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Nginx Proxy Configuration
      - VIRTUAL_HOST=pixel-play.local
      - VIRTUAL_PORT=3000
      # Add your API keys here or in a .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - proxy
    # env_file:
    #   - .env

networks:
  proxy:
    external: true
    name: proxy_network
